# Build configuration for build_runner
# Configures builders for code generation

targets:
  $default:
    builders:
      # Run freezed code generation
      freezed:
        enabled: true
      # Run riverpod_generator
      riverpod_generator:
        enabled: true
      # Skip problematic builders
      custom_lint:
        enabled: false
