name: faiseur
description: "A cross-platform todo app with Firebase backend"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^5.5.1
  cloud_functions: ^5.2.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1

dev_dependencies:
  analyzer_plugin: ^0.13.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
